package com.jqbian.lucene.cookbook.chapter06;

import java.io.IOException;

import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.StringField;
import org.apache.lucene.document.TextField;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexReader;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.index.Term;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.queryparser.classic.QueryParser;
import org.apache.lucene.search.BooleanClause;
import org.apache.lucene.search.BooleanQuery;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.ScoreDoc;
import org.apache.lucene.search.TermQuery;
import org.apache.lucene.search.TermRangeQuery;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.RAMDirectory;
import org.apache.lucene.util.QueryBuilder;
import org.junit.Test;
import org.apache.lucene.document.Field;
import org.apache.lucene.document.FieldType;
import org.apache.lucene.document.IntPoint;
import org.apache.lucene.document.NumericDocValuesField;
import org.apache.lucene.document.StoredField;

public class QueryTermTest01 extends BaseQueryTerm{
		
	
	
	@Test
	public void testQueryTerms() throws IOException{
		Analyzer analyzer = new StandardAnalyzer();		
		Directory directory = new RAMDirectory();
		this.prepareData(directory);
		IndexReader indexReader = DirectoryReader.open(directory);
		IndexSearcher indexSearcher = new IndexSearcher(indexReader);
		//Query query = new TermQuery(new Term("content", "humpty"));
		//BooleanQuery bquery= new BooleanQuery();		
		TermRangeQuery termRange = TermRangeQuery.newStringRange("name", "A", "G", true, true);		
		Query query = new BooleanQuery.Builder().add(new QueryBuilder(analyzer).createBooleanQuery("content", "humpty"),BooleanClause.Occur.MUST).add(termRange, BooleanClause.Occur.MUST).build();
		//new TermQuery(new Term("content", "humpty")).
		//TermRangeFilter termRangeFilter =			TermRangeFilter.newStringRange("name", "A", "G", true, true);
		TopDocs topDocs = indexSearcher.search(query, 100);
		//indexSearcher.search
		System.out.println("Searching 'humpty'");
		for (ScoreDoc scoreDoc : topDocs.scoreDocs) {
			Document doc = indexReader.document(scoreDoc.doc);
			if(doc!=null){
				System.out.println("name: " +	doc.getField("name").stringValue() +" - content: " +doc.getField("content").stringValue() +	" - num: " +doc.getField("num").stringValue());
			}
		}
		indexReader.close();
	}
	
	@Test
	public void testQueryParse() throws IOException, ParseException{
		Directory directory = new RAMDirectory();
		Analyzer analyzer = new StandardAnalyzer();		
		this.prepareData(directory);
		IndexReader indexReader = DirectoryReader.open(directory);
		IndexSearcher indexSearcher = new IndexSearcher(indexReader);
		QueryParser queryParser = new QueryParser("content", analyzer);
		// configure queryParser here
		Query query = queryParser.parse("humpty*");
		TopDocs topDocs = indexSearcher.search(query, 100);
		for (ScoreDoc scoreDoc : topDocs.scoreDocs) {
			Document doc = indexReader.document(scoreDoc.doc);
			if(doc!=null){
				System.out.println("name: " +	doc.getField("name").stringValue() +" - content: " +doc.getField("content").stringValue() +	" - num: " +doc.getField("num").stringValue());
			}
		}
	}
	
	@Test
	public void testQueryParseRange() throws IOException, ParseException{
		Directory directory = new RAMDirectory();
		Analyzer analyzer = new StandardAnalyzer();		
		this.prepareData(directory);
		IndexReader indexReader = DirectoryReader.open(directory);
		IndexSearcher indexSearcher = new IndexSearcher(indexReader);
		QueryParser queryParser = new QueryParser("content", analyzer);
		// configure queryParser here
		Query query = queryParser.parse("[dd TO ff]");
		TopDocs topDocs = indexSearcher.search(query, 100);
		for (ScoreDoc scoreDoc : topDocs.scoreDocs) {
			Document doc = indexReader.document(scoreDoc.doc);
			if(doc!=null){
				System.out.println("name: " +	doc.getField("name").stringValue() +" - content: " +doc.getField("content").stringValue() +	" - num: " +doc.getField("num").stringValue());
			}
		}		
	}
	
	@Test
	public void testQueryAutogenerated() throws IOException, ParseException{
		Directory directory = new RAMDirectory();
		Analyzer analyzer = new StandardAnalyzer();		
		this.prepareData(directory);
		IndexReader indexReader = DirectoryReader.open(directory);
		IndexSearcher indexSearcher = new IndexSearcher(indexReader);
		QueryParser queryParser = new QueryParser("content", analyzer);
		// configure queryParser here
		//Query query = queryParser.parse("[dd TO ff]");
		queryParser.setAutoGeneratePhraseQueries(true);
		Query query = queryParser.parse("humpty+dumpty+sat");
		TopDocs topDocs = indexSearcher.search(query, 100);
		for (ScoreDoc scoreDoc : topDocs.scoreDocs) {
			Document doc = indexReader.document(scoreDoc.doc);
			if(doc!=null){
				System.out.println("name: " +	doc.getField("name").stringValue() +" - content: " +doc.getField("content").stringValue() +	" - num: " +doc.getField("num").stringValue());
			}
		}
	}
	
	@Test 
	public void testDefaultOperator() throws IOException, ParseException{
		Directory directory = new RAMDirectory();
		Analyzer analyzer = new StandardAnalyzer();		
		this.prepareData(directory);
		IndexReader indexReader = DirectoryReader.open(directory);
		IndexSearcher indexSearcher = new IndexSearcher(indexReader);
		QueryParser queryParser = new QueryParser("content", analyzer);
		// configure queryParser here
		//Query query = queryParser.parse("[dd TO ff]");
		//queryParser.setAutoGeneratePhraseQueries(true);
		queryParser.setDefaultOperator(QueryParser.Operator.AND);
		Query query = queryParser.parse("humpty dumpty");
		TopDocs topDocs = indexSearcher.search(query, 100);
		for (ScoreDoc scoreDoc : topDocs.scoreDocs) {
			Document doc = indexReader.document(scoreDoc.doc);
			if(doc!=null){
				System.out.println("name: " +	doc.getField("name").stringValue() +" - content: " +doc.getField("content").stringValue() +	" - num: " +doc.getField("num").stringValue());
			}
		}		
	}
	
	@Test
	public void testFuzzyQuery() throws IOException, ParseException{
		Directory directory = new RAMDirectory();
		Analyzer analyzer = new StandardAnalyzer();		
		this.prepareData(directory);
		IndexReader indexReader = DirectoryReader.open(directory);
		IndexSearcher indexSearcher = new IndexSearcher(indexReader);
		QueryParser queryParser = new QueryParser("content", analyzer);
		// configure queryParser here
		//Query query = queryParser.parse("[dd TO ff]");
		//queryParser.setAutoGeneratePhraseQueries(true);
		//queryParser.setDefaultOperator(QueryParser.Operator.AND);
		//Query query = queryParser.parse("humpty dumpty");
		queryParser.setFuzzyMinSim(2f);
		queryParser.setFuzzyPrefixLength(3);
		Query query = queryParser.parse("hump~");
		TopDocs topDocs = indexSearcher.search(query, 100);
		for (ScoreDoc scoreDoc : topDocs.scoreDocs) {
			Document doc = indexReader.document(scoreDoc.doc);
			if(doc!=null){
				System.out.println("name: " +	doc.getField("name").stringValue() +" - content: " +doc.getField("content").stringValue() +	" - num: " +doc.getField("num").stringValue());
			}
		}
	}
	
	@Test
	public void testPhraseSlop() throws IOException, ParseException{
		Directory directory = new RAMDirectory();
		Analyzer analyzer = new StandardAnalyzer();		
		this.prepareData(directory);
		IndexReader indexReader = DirectoryReader.open(directory);
		IndexSearcher indexSearcher = new IndexSearcher(indexReader);
		QueryParser queryParser = new QueryParser("content", analyzer);
		// configure queryParser here
		//Query query = queryParser.parse("[dd TO ff]");
		//queryParser.setAutoGeneratePhraseQueries(true);
		//queryParser.setDefaultOperator(QueryParser.Operator.AND);
		//Query query = queryParser.parse("humpty dumpty");
		//queryParser.setFuzzyMinSim(2f);
		//queryParser.setFuzzyPrefixLength(3);
		//Query query = queryParser.parse("hump~");
		queryParser.setPhraseSlop(3);
		Query query = queryParser.parse("\"Humpty Dumpty wall\"");
		TopDocs topDocs = indexSearcher.search(query, 100);
		for (ScoreDoc scoreDoc : topDocs.scoreDocs) {
			Document doc = indexReader.document(scoreDoc.doc);
			if(doc!=null){
				System.out.println("name: " +	doc.getField("name").stringValue() +" - content: " +doc.getField("content").stringValue() +	" - num: " +doc.getField("num").stringValue());
			}
		}		
	}
	
	
}
